### ISSUE TITLE
Error installing from NPM:  ENOENT: no such file or directory

### ISSUE THREAD

**Issue by infinisuite** [agrotis-io/docnator#23]
### What are you reporting?

[ X] Bug that needs fixing

### What is the current behavior?

Command: npm install docnator

Error Message:

path /Users/user/Projects/is/0.0.36/client/node_modules/docnator/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user/Projects/is/0.0.36/client/node_modules/docnator/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

### What's your environment?
- OSX

**Comment by jhserodio** [comment]
thanks for your bugfix report @infinisuite , whats your npm version ?
